import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalNavBar } from "@/components/GlobalNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-center">
          <h1>Main layout</h1>
          <p>
            The component <code>RootLayout</code> exported in{" "}
            <code>src/app/layout.tsx</code> is a wrapper of all the pages
          </p>
          <p>
            We can move from one page to another by using the <code>Link</code>{" "}
            imported by <code>next/link</code>
          </p>
        </header>
        <div className="flex">
          <div className="w-[20%]">
            <GlobalNavBar />
          </div>
          <div className="w-[80%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
